import { createContext, useContext, useState, useEffect, ReactNode } from "react";

interface AppSettingsContextType {
  currency: string;
  setCurrency: (currency: string) => void;
  language: string;
  setLanguage: (language: string) => void;
  formatCurrency: (value: number) => string;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  "en-US": {
    "nav.home": "Home",
    "nav.assistant": "Assistant",
    "nav.documents": "Documents",
    "nav.money": "Money",
    "nav.companies": "Ecosystem",
    "nav.billing": "Billing",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "settings.subtitle": "Customize your app and set up your business",
    "settings.branding": "Branding & Identity",
    "settings.brandingDesc": "Set up your company name, logo and information",
    "settings.preferences": "Preferences",
    "settings.preferencesDesc": "Language, currency and other system preferences",
    "settings.setup": "Initial Setup",
    "settings.setupDesc": "Redo the setup wizard to update your business type and receive new suggested links",
    "settings.saved": "Settings saved successfully!",
    "settings.companyLogo": "Company Logo",
    "settings.logoHint": "PNG, JPG up to 2MB",
    "settings.logoPlaceholder": "Logo URL (e.g. https://...)",
    "settings.companyName": "Company Name",
    "settings.businessType": "Business Type",
    "settings.selectPlaceholder": "Select...",
    "settings.ownerName": "Owner Name",
    "settings.email": "Email",
    "settings.phone": "Phone",
    "settings.address": "Address",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.redoSetup": "Redo Initial Setup",
    "settings.saveChanges": "Save Changes",
    "settings.confirmRedo": "Redo Configuration?",
    "settings.confirmRedoDesc": "You are about to redo the initial setup. Existing links will be kept, but new links will be added based on the new business type selected.",
    "settings.continue": "Continue",
    "settings.errorSaving": "Error saving settings",
    "common.add": "Add",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.noResults": "No results found",
    "common.export": "Export",
    "common.total": "Total",
    "common.result": "Result",
    "common.settings": "Settings",
    "common.report": "Report",
    "common.logout": "Logout",
    "common.viewAll": "View all",
    "common.clearHistory": "Clear history",
    "common.newConversation": "New conversation",
    "common.notes": "Notes",
    "common.date": "Date",
    "common.description": "Description",
    "common.optional": "optional",
    "money.title": "Financial Control",
    "money.subtitle": "Complete financial control",
    "money.income": "Income",
    "money.incomeTotal": "Total Income",
    "money.expenses": "Expenses",
    "money.expensesTotal": "Total Expenses",
    "money.sources": "Income Sources",
    "money.sourcesDesc": "Manage your income sources",
    "money.categoriesDesc": "Manage expenses by category",
    "money.addSource": "Source",
    "money.addCategory": "Category",
    "money.newSource": "New Income Source",
    "money.newCategory": "New Category",
    "money.taxPercent": "Tax (%)",
    "money.noSources": "No sources added. Click Source to add.",
    "money.noCategories": "No categories added. Click Category to add.",
    "money.annualReport": "Annual Summary",
    "money.reportDesc": "Consolidated financial view",
    "money.settingsTitle": "Financial Settings",
    "money.settingsDesc": "Manage sources and categories",
    "money.sourceAdded": "Source added!",
    "money.categoryAdded": "Category added!",
    "money.errorAddSource": "Error adding source",
    "money.errorAddCategory": "Error adding category",
    "money.errorLoadData": "Error loading data",
    "money.addTransaction": "Add Transaction",
    "money.selectSource": "Select source...",
    "money.selectCategory": "Select category...",
    "money.sourceName": "Source name",
    "money.categoryName": "Category name",
    "money.amount": "Amount",
    "money.month": "Month",
    "money.addIncome": "Add Income",
    "money.addExpense": "Add Expense",
    "money.notesPlaceholder": "Additional notes...",
    "money.scanReceipt": "Scan Receipt",
    "money.takePhoto": "Take Photo",
    "money.uploadImage": "Upload Image",
    "money.analyzing": "Analyzing...",
    "money.extractedData": "Extracted Data",
    "money.receiptAnalyzed": "Receipt analyzed successfully!",
    "money.errorAnalyzing": "Error analyzing receipt",
    "money.fileTooLarge": "File too large (max 4MB)",
    "money.errorProcessing": "Error processing image",
    "money.merchant": "Merchant",
    "money.type": "Type",
    "money.category": "Category",
    "money.date": "Date",
    "money.retry": "Retry",
    "money.useData": "Use This Data",
    "money.scanReceiptDesc": "Take a photo or upload an image of your receipt",
    "money.noSourcesHint": "No sources yet. Create one below:",
    "money.noCategoriesHint": "No categories yet. Create one below:",
    "money.errorUpdateValue": "Error updating value",
    "money.importStatement": "Import Statement",
    "money.importBankStatement": "Import Bank Statement",
    "money.selectFile": "Select File",
    "money.dropOrClick": "Drop file here or click to upload",
    "money.transactions": "transactions",
    "money.changeFile": "Change file",
    "money.defaultSource": "Default Source",
    "money.defaultCategory": "Default Category",
    "money.import": "Import",
    "money.transactionsImported": "transactions imported",
    "money.errorParseFile": "Error parsing file",
    "money.selectTransactions": "Select at least one transaction",
    "money.errorImport": "Error importing transactions",
    "ecosystem.title": "Ecosystem Hub",
    "ecosystem.name": "Name",
    "ecosystem.noLinks": "No links in this category",
    "ecosystem.companies": "Companies",
    "ecosystem.links": "Links",
    "ecosystem.allCompanies": "All companies",
    "ecosystem.clearSelection": "Clear selection",
    "ecosystem.subCompanies": "sub-companies",
    "ecosystem.addSubCompany": "Add sub-company",
    "ecosystem.unlinkedSatellites": "Unlinked satellites",
    "ecosystem.noCompanies": "No companies yet",
    "settings.accounts": "Accounts",
    "settings.expenseCategories": "Expense Cat.",
    "settings.incomeCategories": "Income Cat.",
    "settings.incomeTypes": "Income Types",
    "settings.addItem": "Add",
    "settings.noItems": "No items registered",
    "settings.actions": "Actions",
    "settings.selectCompany": "Edit Company",
    "settings.globalSettings": "Global Settings",
    "priority.critical": "Critical",
    "priority.high": "High",
    "priority.medium": "Medium",
    "priority.low": "Low",
    "home.summary": "Here's your business ecosystem summary",
    "home.monthlyIncome": "Monthly Income",
    "home.monthlyExpenses": "Monthly Expenses",
    "home.monthlyBalance": "Monthly Balance",
    "home.ecosystemLinks": "Ecosystem Links",
    "home.companies": "Companies",
    "home.companiesRegistered": "companies registered",
    "home.documents": "Documents",
    "home.documentsSaved": "documents saved",
    "home.godModeActive": "God Mode Active",
    "home.godModeDesc": "Your second mind is ready. Control everything by voice or text.",
    "home.activate": "Activate",
    "home.aiAssistant": "AI Assistant",
    "home.tipTitle": "God Mode Tip",
    "home.tipDesc": "Try saying \"Show my financial summary\" or \"What are my most important links?\" in God Mode for quick insights.",
    "home.quickActions": "Quick Actions",
    "home.profitLoss": "Profit & Loss",
    "home.netIncome": "Net Income",
    "home.consolidatedView": "Consolidated View",
    "documents.title": "Documents",
    "documents.saved": "documents saved",
    "documents.search": "Search documents...",
    "documents.category": "Category",
    "documents.all": "All",
    "documents.add": "Add",
    "documents.addDocument": "Add Document",
    "documents.upload": "Upload",
    "documents.link": "Link",
    "documents.name": "Name",
    "documents.fileUrl": "File URL",
    "documents.noDocuments": "No documents found",
    "documents.clickToAdd": "Click \"Add\" to create your first document",
    "documents.noDocCategory": "No documents",
    "documents.contracts": "Contracts",
    "documents.invoices": "Invoices",
    "documents.receipts": "Receipts",
    "documents.legal": "Legal Documents",
    "documents.financial": "Financial",
    "documents.other": "Other",
    "documents.categories": "Categories",
    "documents.manageCategories": "Manage Categories",
    "documents.newCategoryName": "New category name",
    "documents.customCategories": "Custom Categories",
    "documents.noCustomCategories": "No custom categories. Create one above!",
    "documents.defaultCategories": "Default Categories",
    "documents.categoryExists": "Category already exists",
    "documents.categoryAdded": "Category added!",
    "assistant.hello": "Hello!",
    "assistant.howCanHelp": "How can I help you today?",
    "assistant.listening": "Listening... speak naturally",
    "assistant.reviewSend": "Review and press Enter or click send",
    "assistant.typeOrMic": "Type or click the mic...",
    "assistant.speechHere": "Your speech will appear here...",
    "toast.companyUpdated": "Company updated!",
    "toast.companyCreated": "Company created!",
    "toast.errorSaving": "Error saving",
    "toast.fillRequired": "Please fill all required fields",
    "toast.linkAdded": "Link added!",
    "toast.errorAdding": "Error adding",
    "toast.linkRemoved": "Link removed!",
    "toast.errorRemoving": "Error removing",
    "toast.companyRemoved": "Company removed!",
    "company.type": "Type",
    "company.mainCompany": "Main Company",
    "company.subsidiary": "Subsidiary/Related",
    "company.parentCompany": "Parent Company",
    "company.selectParent": "Select parent company...",
    "company.name": "Company Name",
    "company.satellite": "Satellite",
    "company.about": "About",
    "company.aboutPlaceholder": "Describe your company, mission, and services...",
    "company.logoUrl": "Logo URL",
    "company.overview": "Overview",
    "company.manage": "Manage",
    "company.tips": "Tips",
    "company.employees": "Employees",
    "company.clients": "Clients",
    "company.providers": "Providers",
    "company.aboutTitle": "About Company",
    "company.noDescription": "No description added yet. Click edit to add one.",
    "company.active": "Active",
    "company.tipsTitle": "Getting Started",
    "company.tipsDesc": "Here are some tips to help you manage your company effectively.",
    "company.tipEmployees": "Add employees to track your team members, their roles, and hourly rates.",
    "company.tipClients": "Register clients to manage your customer relationships and contacts.",
    "company.tipDocuments": "Upload important documents like contracts, invoices, and receipts.",
    "company.tipFinances": "Set up income sources and expense categories to track your finances.",
    "company.quickActions": "Quick Actions",
    "company.addEmployee": "+ Employee",
    "company.addClient": "+ Client",
    "company.addDocument": "+ Document",
    "company.websiteUrl": "Website",
    "company.contactEmail": "Email",
    "company.contactPhone": "Phone",
    "company.socialLinks": "Social Links",
    "company.services": "Services",
    "company.servicesPlaceholder": "List your main services...",
    "company.coverImage": "Cover Image URL",
    "company.changeCover": "Change Cover",
    "company.imageUploaded": "Image uploaded successfully!",
    "company.uploadError": "Error uploading image",
    "company.fileTooLarge": "File too large (max 5MB)",
    "company.mission": "Mission",
    "company.missionPlaceholder": "What is your company's mission?",
    "company.portfolio": "Portfolio",
    "company.manageLinks": "Manage Links",
    "company.noLinks": "No links registered",
    "company.addLinkHint": "Add useful links for your company",
    "company.addLink": "Add Link",
    "company.linkCategory": "Category",
    "company.linkName": "Name",
    "company.linkUrl": "URL",
    "company.linkNameUrlRequired": "Name and URL are required",
    "company.linkAdded": "Link added!",
    "company.linkUpdated": "Link updated!",
    "company.linkDeleted": "Link removed!",
    "company.linkError": "Error saving link",
    "admin.tenants": "Admin - Tenants",
    "admin.tenantsDesc": "Manage all platform clients/tenants",
    "admin.newTenant": "New Tenant",
    "admin.searchTenants": "Search by name, slug or email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.tenant": "Tenant",
    "admin.domain": "Domain",
    "admin.owner": "Owner",
    "admin.status": "Status",
    "admin.share": "Share",
    "admin.actions": "Actions",
    "admin.noTenantFound": "No tenant found",
    "admin.noTenantRegistered": "No tenant registered",
    "admin.activeStatus": "Active",
    "admin.inactiveStatus": "Inactive",
    "admin.copyLink": "Copy link",
    "admin.sendWhatsApp": "Send via WhatsApp",
    "admin.sendEmail": "Send via Email",
    "admin.generatePDF": "Generate PDF",
    "admin.remixGuide": "Remix Guide",
    "admin.editTenant": "Edit Tenant",
    "admin.createTenant": "Create Tenant",
    "admin.updateInfo": "Update tenant information",
    "admin.fillData": "Fill in the data to create a new tenant",
    "admin.name": "Name",
    "admin.slug": "Slug",
    "admin.customDomain": "Custom Domain",
    "admin.ownerName": "Owner Name",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Phone (WhatsApp)",
    "admin.businessType": "Business Type",
    "admin.primaryColor": "Primary Color",
    "admin.logoUrl": "Logo URL",
    "admin.requiredFields": "Name and slug are required",
    "admin.tenantUpdated": "Tenant updated!",
    "admin.tenantCreated": "Tenant created!",
    "admin.slugExists": "Slug or domain already exists",
    "admin.errorSaving": "Error saving tenant",
    "admin.confirmDelete": "Confirm Deletion",
    "admin.deleteWarning": "Are you sure you want to delete this tenant? This action cannot be undone and all associated data will be lost.",
    "admin.tenantRemoved": "Tenant removed!",
    "admin.errorDeleting": "Error deleting tenant",
    "admin.tenantActivated": "Tenant activated",
    "admin.tenantDeactivated": "Tenant deactivated",
    "admin.errorUpdating": "Error updating tenant",
    "admin.errorLoading": "Error loading tenants",
    "admin.accessDenied": "Access denied. Only super admins can access this page.",
    "admin.linkCopied": "Link copied!",
    "admin.remixGuideTitle": "Remix Guide",
    "admin.remixGuideDesc": "Follow the steps below to create an isolated project for this client",
    "admin.clientData": "CLIENT DATA",
    "admin.stepByStep": "STEP BY STEP",
    "admin.step1Title": "Remix the Project",
    "admin.step1Desc": "Click on project name → Settings → Remix",
    "admin.step2Title": "Activate Lovable Cloud",
    "admin.step2Desc": "In the new project, activate Cloud for isolated database",
    "admin.step3Title": "Customize",
    "admin.step3Desc": "Change colors and add logo if needed",
    "admin.step4Title": "Configure Domain",
    "admin.step4Desc": "Settings → Domains → Add",
    "admin.step5Title": "Transfer to Client",
    "admin.step5Desc": "Settings → Transfer → Send to",
    "admin.copyChecklist": "Copy Checklist",
    "admin.close": "Close",
    "admin.infoCopied": "Information copied!",
    "admin.cleaning": "Cleaning",
    "admin.restaurant": "Restaurant",
    "admin.construction": "Construction",
    "admin.retail": "Retail",
    "admin.tech": "Technology",
    "admin.health": "Health",
    "admin.education": "Education",
    "admin.other": "Other",
    // Billing page translations
    "billing.title": "Plans & Billing",
    "billing.subtitle": "Choose the ideal plan for your business",
    "billing.yourSubscription": "Your Subscription",
    "billing.planName": "Plan",
    "billing.renewalDate": "Renewal on",
    "billing.active": "Active",
    "billing.manageSubscription": "Manage Subscription",
    "billing.mostPopular": "Most Popular",
    "billing.yourPlan": "Your Plan",
    "billing.currentPlan": "Current Plan",
    "billing.changePlan": "Change Plan",
    "billing.subscribeNow": "Subscribe Now",
    "billing.loginToSubscribe": "Log in to subscribe",
    "billing.securePayment": "Secure payment processed by Stripe",
    "billing.features.financial": "Complete financial management",
    "billing.features.companies": "Company management",
    "billing.features.documents": "Unlimited documents",
    "billing.features.godMode": "God Mode AI Assistant",
    "billing.features.support": "Priority support",
    "billing.success": "Subscription activated successfully!",
    "billing.welcome": "Welcome to Ecosystem Hub!",
    "billing.canceled": "Checkout canceled",
    "billing.canceledDesc": "You can subscribe at any time.",
    "billing.checkoutError": "Checkout error",
    "billing.portalError": "Error opening portal",
    "billing.perMonth": "month",
    "billing.perMonths": "months",
    "billing.perYear": "year",
    "billing.save": "Save",
  },
  "pt-BR": {
    "nav.home": "Início",
    "nav.assistant": "Assistente",
    "nav.documents": "Documentos",
    "nav.money": "Dinheiro",
    "nav.companies": "Empresas",
    "nav.billing": "Cobrança",
    "nav.settings": "Config",
    "nav.help": "Ajuda",
    "settings.subtitle": "Personalize seu app e configure seu negócio",
    "settings.branding": "Branding & Identidade",
    "settings.brandingDesc": "Configure o nome, logo e informações da sua empresa",
    "settings.preferences": "Preferências",
    "settings.preferencesDesc": "Idioma, moeda e outras preferências do sistema",
    "settings.setup": "Configuração Inicial",
    "settings.setupDesc": "Refaça o assistente de configuração para atualizar seu tipo de negócio",
    "settings.saved": "Configurações salvas com sucesso!",
    "settings.companyLogo": "Logo da Empresa",
    "settings.logoHint": "PNG, JPG até 2MB",
    "settings.logoPlaceholder": "URL do logo (ex: https://...)",
    "settings.companyName": "Nome da Empresa",
    "settings.businessType": "Tipo de Negócio",
    "settings.selectPlaceholder": "Selecione...",
    "settings.ownerName": "Nome do Proprietário",
    "settings.email": "Email",
    "settings.phone": "Telefone",
    "settings.address": "Endereço",
    "settings.language": "Idioma",
    "settings.currency": "Moeda",
    "settings.redoSetup": "Refazer Setup Inicial",
    "settings.saveChanges": "Salvar Alterações",
    "settings.confirmRedo": "Refazer Configuração?",
    "settings.confirmRedoDesc": "Você está prestes a refazer o setup inicial. Os links existentes serão mantidos, mas novos links serão adicionados baseados no novo tipo de negócio selecionado.",
    "settings.continue": "Continuar",
    "settings.errorSaving": "Erro ao salvar configurações",
    "common.add": "Adicionar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.loading": "Carregando...",
    "common.noResults": "Nenhum resultado",
    "common.export": "Exportar",
    "common.total": "Total",
    "common.result": "Resultado",
    "common.settings": "Config",
    "common.report": "Relatório",
    "common.logout": "Sair",
    "common.viewAll": "Ver todos",
    "common.clearHistory": "Limpar histórico",
    "common.newConversation": "Nova conversa",
    "common.notes": "Notas",
    "common.date": "Data",
    "common.description": "Descrição",
    "common.optional": "opcional",
    "money.title": "Controle Financeiro",
    "money.subtitle": "Controle financeiro completo",
    "money.income": "Receitas",
    "money.incomeTotal": "Receita Total",
    "money.expenses": "Despesas",
    "money.expensesTotal": "Despesas Totais",
    "money.sources": "Fontes de Receita",
    "money.sourcesDesc": "Gerencie suas fontes de renda",
    "money.categoriesDesc": "Gerencie seus gastos por categoria",
    "money.addSource": "Fonte",
    "money.addCategory": "Categoria",
    "money.newSource": "Nova Fonte de Receita",
    "money.newCategory": "Nova Categoria",
    "money.taxPercent": "Imposto (%)",
    "money.noSources": "Nenhuma fonte cadastrada. Clique em Fonte para adicionar.",
    "money.noCategories": "Nenhuma categoria cadastrada. Clique em Categoria para adicionar.",
    "money.annualReport": "Resumo Anual",
    "money.reportDesc": "Visão consolidada das finanças",
    "money.settingsTitle": "Configurações Financeiras",
    "money.settingsDesc": "Gerencie fontes e categorias",
    "money.sourceAdded": "Fonte adicionada!",
    "money.categoryAdded": "Categoria adicionada!",
    "money.errorAddSource": "Erro ao adicionar fonte",
    "money.errorAddCategory": "Erro ao adicionar categoria",
    "money.errorLoadData": "Erro ao carregar dados",
    "money.errorUpdateValue": "Erro ao atualizar valor",
    "money.addTransaction": "Adicionar Transação",
    "money.selectSource": "Selecionar fonte...",
    "money.selectCategory": "Selecionar categoria...",
    "money.sourceName": "Nome da fonte",
    "money.categoryName": "Nome da categoria",
    "money.amount": "Valor",
    "money.month": "Mês",
    "money.addIncome": "Adicionar Receita",
    "money.addExpense": "Adicionar Despesa",
    "money.notesPlaceholder": "Observações...",
    "money.scanReceipt": "Escanear Recibo",
    "money.takePhoto": "Tirar Foto",
    "money.uploadImage": "Enviar Imagem",
    "money.analyzing": "Analisando...",
    "money.extractedData": "Dados Extraídos",
    "money.receiptAnalyzed": "Recibo analisado com sucesso!",
    "money.errorAnalyzing": "Erro ao analisar recibo",
    "money.fileTooLarge": "Arquivo muito grande (max 4MB)",
    "money.errorProcessing": "Erro ao processar imagem",
    "money.merchant": "Estabelecimento",
    "money.type": "Tipo",
    "money.category": "Categoria",
    "money.date": "Data",
    "money.retry": "Tentar Novamente",
    "money.useData": "Usar Esses Dados",
    "money.scanReceiptDesc": "Tire uma foto ou envie uma imagem do seu recibo",
    "money.noSourcesHint": "Nenhuma fonte. Crie uma abaixo:",
    "money.noCategoriesHint": "Nenhuma categoria. Crie uma abaixo:",
    "money.importStatement": "Importar Extrato",
    "money.importBankStatement": "Importar Extrato Bancário",
    "money.selectFile": "Selecionar Arquivo",
    "money.dropOrClick": "Arraste aqui ou clique para enviar",
    "money.transactions": "transações",
    "money.changeFile": "Trocar arquivo",
    "money.defaultSource": "Fonte Padrão",
    "money.defaultCategory": "Categoria Padrão",
    "money.import": "Importar",
    "money.transactionsImported": "transações importadas",
    "money.errorParseFile": "Erro ao analisar arquivo",
    "money.selectTransactions": "Selecione pelo menos uma transação",
    "money.errorImport": "Erro ao importar transações",
    "ecosystem.title": "Ecossistema Hub",
    "ecosystem.name": "Nome",
    "ecosystem.noLinks": "Nenhum link nesta categoria",
    "ecosystem.companies": "Empresas",
    "ecosystem.links": "Links",
    "ecosystem.allCompanies": "Todas as empresas",
    "ecosystem.clearSelection": "Limpar seleção",
    "ecosystem.subCompanies": "sub-empresas",
    "ecosystem.addSubCompany": "Adicionar sub-empresa",
    "ecosystem.unlinkedSatellites": "Satélites não vinculados",
    "ecosystem.noCompanies": "Nenhuma empresa ainda",
    "settings.accounts": "Contas",
    "settings.expenseCategories": "Cat. Despesas",
    "settings.incomeCategories": "Cat. Receitas",
    "settings.incomeTypes": "Tipos Receita",
    "settings.addItem": "Adicionar",
    "settings.noItems": "Nenhum item cadastrado",
    "settings.actions": "Ações",
    "settings.selectCompany": "Editar Empresa",
    "settings.globalSettings": "Configurações Globais",
    "priority.critical": "Crítico",
    "priority.high": "Alto",
    "priority.medium": "Médio",
    "priority.low": "Baixo",
    "home.summary": "Aqui está o resumo do seu ecossistema empresarial",
    "home.monthlyIncome": "Receita do mês",
    "home.monthlyExpenses": "Despesas do mês",
    "home.monthlyBalance": "Saldo do mês",
    "home.ecosystemLinks": "Links no Ecosystem",
    "home.companies": "Empresas",
    "home.companiesRegistered": "empresas cadastradas",
    "home.documents": "Documentos",
    "home.documentsSaved": "documentos salvos",
    "home.godModeActive": "God Mode Ativo",
    "home.godModeDesc": "Sua segunda mente está pronta. Controle tudo por voz ou texto.",
    "home.activate": "Ativar",
    "home.aiAssistant": "Inteligência Artificial",
    "home.tipTitle": "Dica do God Mode",
    "home.tipDesc": "Experimente dizer \"Mostre meu resumo financeiro\" ou \"Quais são meus links mais importantes?\" no God Mode para obter insights rápidos.",
    "home.quickActions": "Ações Rápidas",
    "home.profitLoss": "Lucros e Perdas",
    "home.netIncome": "Lucro Líquido",
    "home.consolidatedView": "Visão Consolidada",
    "documents.title": "Documentos",
    "documents.saved": "documentos salvos",
    "documents.search": "Buscar documentos...",
    "documents.category": "Categoria",
    "documents.all": "Todas",
    "documents.add": "Adicionar",
    "documents.addDocument": "Adicionar Documento",
    "documents.upload": "Upload",
    "documents.link": "Link",
    "documents.name": "Nome",
    "documents.fileUrl": "URL do arquivo",
    "documents.noDocuments": "Nenhum documento encontrado",
    "documents.clickToAdd": "Clique em \"Adicionar\" para criar seu primeiro documento",
    "documents.noDocCategory": "Nenhum documento",
    "documents.contracts": "Contratos",
    "documents.invoices": "Notas Fiscais",
    "documents.receipts": "Recibos",
    "documents.legal": "Documentos Legais",
    "documents.financial": "Financeiro",
    "documents.other": "Outros",
    "documents.categories": "Categorias",
    "documents.manageCategories": "Gerenciar Categorias",
    "documents.newCategoryName": "Nome da nova categoria",
    "documents.customCategories": "Categorias Personalizadas",
    "documents.noCustomCategories": "Sem categorias personalizadas. Crie uma acima!",
    "documents.defaultCategories": "Categorias Padrão",
    "documents.categoryExists": "Categoria já existe",
    "documents.categoryAdded": "Categoria adicionada!",
    "assistant.hello": "Olá!",
    "assistant.howCanHelp": "Como posso te ajudar hoje?",
    "assistant.listening": "Ouvindo... fale naturalmente",
    "assistant.reviewSend": "Revise e pressione Enter ou clique em enviar",
    "assistant.typeOrMic": "Digite ou clique no mic...",
    "assistant.speechHere": "Sua fala aparecerá aqui...",
    "toast.companyUpdated": "Empresa atualizada!",
    "toast.companyCreated": "Empresa criada!",
    "toast.errorSaving": "Erro ao salvar",
    "toast.fillRequired": "Preencha todos os campos obrigatórios",
    "toast.linkAdded": "Link adicionado!",
    "toast.errorAdding": "Erro ao adicionar",
    "toast.linkRemoved": "Link removido!",
    "toast.errorRemoving": "Erro ao remover",
    "toast.companyRemoved": "Empresa removida!",
    "company.type": "Tipo",
    "company.mainCompany": "Empresa Principal",
    "company.subsidiary": "Filial/Relacionada",
    "company.parentCompany": "Empresa Mãe",
    "company.selectParent": "Selecionar empresa mãe...",
    "company.name": "Nome da Empresa",
    "company.satellite": "Satélite",
    "company.about": "Sobre",
    "company.aboutPlaceholder": "Descreva sua empresa, missão e serviços...",
    "company.logoUrl": "URL do Logo",
    "company.overview": "Visão Geral",
    "company.manage": "Gerenciar",
    "company.tips": "Dicas",
    "company.employees": "Funcionários",
    "company.clients": "Clientes",
    "company.providers": "Fornecedores",
    "company.aboutTitle": "Sobre a Empresa",
    "company.noDescription": "Sem descrição. Clique em editar para adicionar.",
    "company.active": "Ativo",
    "company.tipsTitle": "Primeiros Passos",
    "company.tipsDesc": "Aqui estão algumas dicas para gerenciar sua empresa de forma eficaz.",
    "company.tipEmployees": "Adicione funcionários para acompanhar sua equipe e seus valores por hora.",
    "company.tipClients": "Cadastre clientes para gerenciar seus relacionamentos e contatos.",
    "company.tipDocuments": "Faça upload de documentos importantes como contratos e notas fiscais.",
    "company.tipFinances": "Configure fontes de renda e categorias de despesas para suas finanças.",
    "company.quickActions": "Ações Rápidas",
    "company.addEmployee": "+ Funcionário",
    "company.addClient": "+ Cliente",
    "company.addDocument": "+ Documento",
    "company.websiteUrl": "Website",
    "company.contactEmail": "Email",
    "company.contactPhone": "Telefone",
    "company.socialLinks": "Links Sociais",
    "company.services": "Serviços",
    "company.servicesPlaceholder": "Liste seus principais serviços...",
    "company.coverImage": "Imagem de Capa",
    "company.changeCover": "Alterar Capa",
    "company.imageUploaded": "Imagem enviada com sucesso!",
    "company.uploadError": "Erro ao enviar imagem",
    "company.fileTooLarge": "Arquivo muito grande (máx 5MB)",
    "company.mission": "Missão",
    "company.missionPlaceholder": "Qual é a missão da sua empresa?",
    "company.portfolio": "Portfólio",
    "company.manageLinks": "Gerenciar Links",
    "company.noLinks": "Nenhum link cadastrado",
    "company.addLinkHint": "Adicione links úteis para sua empresa",
    "company.addLink": "Adicionar Link",
    "company.linkCategory": "Categoria",
    "company.linkName": "Nome",
    "company.linkUrl": "URL",
    "company.linkNameUrlRequired": "Nome e URL são obrigatórios",
    "company.linkAdded": "Link adicionado!",
    "company.linkUpdated": "Link atualizado!",
    "company.linkDeleted": "Link removido!",
    "company.linkError": "Erro ao salvar link",
    "admin.tenants": "Admin - Tenants",
    "admin.tenantsDesc": "Gerencie todos os clientes/tenants da plataforma",
    "admin.newTenant": "Novo Tenant",
    "admin.searchTenants": "Buscar por nome, slug ou email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Ativos",
    "admin.inactive": "Inativos",
    "admin.tenant": "Tenant",
    "admin.domain": "Domínio",
    "admin.owner": "Proprietário",
    "admin.status": "Status",
    "admin.share": "Compartilhar",
    "admin.actions": "Ações",
    "admin.noTenantFound": "Nenhum tenant encontrado",
    "admin.noTenantRegistered": "Nenhum tenant cadastrado",
    "admin.activeStatus": "Ativo",
    "admin.inactiveStatus": "Inativo",
    "admin.copyLink": "Copiar link",
    "admin.sendWhatsApp": "Enviar por WhatsApp",
    "admin.sendEmail": "Enviar por Email",
    "admin.generatePDF": "Gerar PDF",
    "admin.remixGuide": "Guia Remix",
    "admin.editTenant": "Editar Tenant",
    "admin.createTenant": "Criar Tenant",
    "admin.updateInfo": "Atualize as informações do tenant",
    "admin.fillData": "Preencha os dados para criar um novo tenant",
    "admin.name": "Nome",
    "admin.slug": "Slug",
    "admin.customDomain": "Domínio Personalizado",
    "admin.ownerName": "Nome do Proprietário",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Telefone (WhatsApp)",
    "admin.businessType": "Tipo de Negócio",
    "admin.primaryColor": "Cor Principal",
    "admin.logoUrl": "URL do Logo",
    "admin.requiredFields": "Nome e slug são obrigatórios",
    "admin.tenantUpdated": "Tenant atualizado!",
    "admin.tenantCreated": "Tenant criado!",
    "admin.slugExists": "Slug ou domínio já existe",
    "admin.errorSaving": "Erro ao salvar tenant",
    "admin.confirmDelete": "Confirmar Exclusão",
    "admin.deleteWarning": "Tem certeza que deseja excluir este tenant? Esta ação não pode ser desfeita e todos os dados associados serão perdidos.",
    "admin.tenantRemoved": "Tenant removido!",
    "admin.errorDeleting": "Erro ao remover tenant",
    "admin.tenantActivated": "Tenant ativado",
    "admin.tenantDeactivated": "Tenant desativado",
    "admin.errorUpdating": "Erro ao atualizar tenant",
    "admin.errorLoading": "Erro ao carregar tenants",
    "admin.accessDenied": "Acesso negado. Apenas super admins podem acessar esta página.",
    "admin.linkCopied": "Link copiado!",
    "admin.remixGuideTitle": "Guia de Remix",
    "admin.remixGuideDesc": "Siga os passos abaixo para criar um projeto isolado para este cliente",
    "admin.clientData": "DADOS DO CLIENTE",
    "admin.stepByStep": "PASSO A PASSO",
    "admin.step1Title": "Fazer Remix do Projeto",
    "admin.step1Desc": "Clique no nome do projeto → Settings → Remix",
    "admin.step2Title": "Ativar Lovable Cloud",
    "admin.step2Desc": "No novo projeto, ative o Cloud para banco isolado",
    "admin.step3Title": "Personalizar",
    "admin.step3Desc": "Altere cores e adicione logo se necessário",
    "admin.step4Title": "Configurar Domínio",
    "admin.step4Desc": "Settings → Domains → Adicionar",
    "admin.step5Title": "Transferir para Cliente",
    "admin.step5Desc": "Settings → Transfer → Enviar para",
    "admin.copyChecklist": "Copiar Checklist",
    "admin.close": "Fechar",
    "admin.infoCopied": "Informações copiadas!",
    "admin.cleaning": "Limpeza",
    "admin.restaurant": "Restaurante",
    "admin.construction": "Construção",
    "admin.retail": "Varejo",
    "admin.tech": "Tecnologia",
    "admin.health": "Saúde",
    "admin.education": "Educação",
    "admin.other": "Outro",
    // Billing page translations
    "billing.title": "Planos e Cobrança",
    "billing.subtitle": "Escolha o plano ideal para seu negócio",
    "billing.yourSubscription": "Sua Assinatura",
    "billing.planName": "Plano",
    "billing.renewalDate": "Renovação em",
    "billing.active": "Ativo",
    "billing.manageSubscription": "Gerenciar Assinatura",
    "billing.mostPopular": "Mais Popular",
    "billing.yourPlan": "Seu Plano",
    "billing.currentPlan": "Plano Atual",
    "billing.changePlan": "Alterar Plano",
    "billing.subscribeNow": "Assinar Agora",
    "billing.loginToSubscribe": "Faça login para assinar",
    "billing.securePayment": "Pagamento seguro processado pelo Stripe",
    "billing.features.financial": "Gestão financeira completa",
    "billing.features.companies": "Gerenciamento de empresas",
    "billing.features.documents": "Documentos ilimitados",
    "billing.features.godMode": "God Mode AI Assistant",
    "billing.features.support": "Suporte prioritário",
    "billing.success": "Assinatura ativada com sucesso!",
    "billing.welcome": "Bem-vindo ao Ecosystem Hub!",
    "billing.canceled": "Checkout cancelado",
    "billing.canceledDesc": "Você pode assinar a qualquer momento.",
    "billing.checkoutError": "Erro no checkout",
    "billing.portalError": "Erro ao abrir portal",
    "billing.perMonth": "mês",
    "billing.perMonths": "meses",
    "billing.perYear": "ano",
    "billing.save": "Economize",
  },
};

const AppSettingsContext = createContext<AppSettingsContextType | undefined>(undefined);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [currency, setCurrencyState] = useState(() => {
    return localStorage.getItem("app_currency") || "BRL";
  });

  const [language, setLanguageState] = useState(() => {
    const saved = localStorage.getItem("app_language");
    // Migrate old languages to supported ones
    if (saved === "en-CA" || saved === "fr-CA" || saved === "es-ES") {
      return "en-US";
    }
    return saved || "pt-BR";
  });

  const setCurrency = (newCurrency: string) => {
    setCurrencyState(newCurrency);
    localStorage.setItem("app_currency", newCurrency);
    window.dispatchEvent(new Event("storage"));
  };

  const setLanguage = (newLanguage: string) => {
    setLanguageState(newLanguage);
    localStorage.setItem("app_language", newLanguage);
    document.documentElement.lang = newLanguage;
  };

  const formatCurrency = (value: number) => {
    const locales: Record<string, string> = {
      BRL: "pt-BR",
      USD: "en-US",
      EUR: "de-DE",
      GBP: "en-GB",
      CAD: "en-CA",
    };

    return new Intl.NumberFormat(locales[currency] || "pt-BR", {
      style: "currency",
      currency: currency,
    }).format(value);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] || translations["en-US"];
    return langTranslations[key] || translations["en-US"][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "app_currency") {
        setCurrencyState(e.newValue || "BRL");
      }
      if (e.key === "app_language") {
        setLanguageState(e.newValue || "pt-BR");
      }
    };
    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, []);

  return (
    <AppSettingsContext.Provider
      value={{
        currency,
        setCurrency,
        language,
        setLanguage,
        formatCurrency,
        t,
      }}
    >
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (context === undefined) {
    throw new Error("useAppSettings must be used within an AppSettingsProvider");
  }
  return context;
}
