import { createContext, useContext, useState, useEffect, ReactNode } from "react";

interface AppSettingsContextType {
  currency: string;
  setCurrency: (currency: string) => void;
  language: string;
  setLanguage: (language: string) => void;
  formatCurrency: (value: number) => string;
  t: (key: string) => string;
}

const translations: Record<string, Record<string, string>> = {
  "en-CA": {
    "nav.home": "Home",
    "nav.assistant": "Assistant",
    "nav.documents": "Documents",
    "nav.money": "Money",
    "nav.companies": "Ecosystem",
    "nav.settings": "Settings",
    "nav.help": "Help",
    "settings.subtitle": "Customize your app and set up your business",
    "settings.branding": "Branding & Identity",
    "settings.brandingDesc": "Set up your company name, logo and information",
    "settings.preferences": "Preferences",
    "settings.preferencesDesc": "Language, currency and other system preferences",
    "settings.setup": "Initial Setup",
    "settings.setupDesc": "Redo the setup wizard to update your business type and receive new suggested links",
    "settings.saved": "Settings saved successfully!",
    "settings.companyLogo": "Company Logo",
    "settings.logoHint": "PNG, JPG up to 2MB",
    "settings.logoPlaceholder": "Logo URL (e.g. https://...)",
    "settings.companyName": "Company Name",
    "settings.businessType": "Business Type",
    "settings.selectPlaceholder": "Select...",
    "settings.ownerName": "Owner Name",
    "settings.email": "Email",
    "settings.phone": "Phone",
    "settings.address": "Address",
    "settings.language": "Language",
    "settings.currency": "Currency",
    "settings.redoSetup": "Redo Initial Setup",
    "settings.saveChanges": "Save Changes",
    "settings.confirmRedo": "Redo Configuration?",
    "settings.confirmRedoDesc": "You are about to redo the initial setup. Existing links will be kept, but new links will be added based on the new business type selected.",
    "settings.continue": "Continue",
    "settings.errorSaving": "Error saving settings",
    "common.add": "Add",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.noResults": "No results found",
    "common.export": "Export",
    "common.total": "Total",
    "common.result": "Result",
    "common.settings": "Settings",
    "common.report": "Report",
    "common.logout": "Logout",
    "common.viewAll": "View all",
    "common.clearHistory": "Clear history",
    "common.newConversation": "New conversation",
    "money.title": "Financial Control",
    "money.subtitle": "Complete financial control",
    "money.income": "Income",
    "money.incomeTotal": "Total Income",
    "money.expenses": "Expenses",
    "money.expensesTotal": "Total Expenses",
    "money.sources": "Income Sources",
    "money.sourcesDesc": "Manage your income sources",
    "money.categoriesDesc": "Manage expenses by category",
    "money.addSource": "Source",
    "money.addCategory": "Category",
    "money.newSource": "New Income Source",
    "money.newCategory": "New Category",
    "money.taxPercent": "Tax (%)",
    "money.noSources": "No sources added. Click Source to add.",
    "money.noCategories": "No categories added. Click Category to add.",
    "money.annualReport": "Annual Summary",
    "money.reportDesc": "Consolidated financial view",
    "money.settingsTitle": "Financial Settings",
    "money.settingsDesc": "Manage sources and categories",
    "money.sourceAdded": "Source added!",
    "money.categoryAdded": "Category added!",
    "money.errorAddSource": "Error adding source",
    "money.errorAddCategory": "Error adding category",
    "money.errorLoadData": "Error loading data",
    "money.addTransaction": "Add Transaction",
    "money.selectSource": "Select source...",
    "money.selectCategory": "Select category...",
    "money.sourceName": "Source name",
    "money.categoryName": "Category name",
    "money.amount": "Amount",
    "money.month": "Month",
    "money.addIncome": "Add Income",
    "money.addExpense": "Add Expense",
    "money.notesPlaceholder": "Additional notes...",
    "money.scanReceipt": "Scan Receipt",
    "money.takePhoto": "Take Photo",
    "money.uploadImage": "Upload Image",
    "money.analyzing": "Analyzing...",
    "money.extractedData": "Extracted Data",
    "money.receiptAnalyzed": "Receipt analyzed successfully!",
    "money.errorAnalyzing": "Error analyzing receipt",
    "money.fileTooLarge": "File too large (max 4MB)",
    "money.errorProcessing": "Error processing image",
    "money.merchant": "Merchant",
    "money.type": "Type",
    "money.category": "Category",
    "money.date": "Date",
    "money.retry": "Retry",
    "money.useData": "Use This Data",
    "money.scanReceiptDesc": "Take a photo or upload an image of your receipt",
    "money.noSourcesHint": "No sources yet. Create one below:",
    "money.noCategoriesHint": "No categories yet. Create one below:",
    "common.notes": "Notes",
    "money.errorUpdateValue": "Error updating value",
    "ecosystem.title": "Ecosystem Hub",
    "ecosystem.name": "Name",
    "ecosystem.noLinks": "No links in this category",
    "ecosystem.companies": "Companies",
    "ecosystem.links": "Links",
    "ecosystem.allCompanies": "All companies",
    "ecosystem.clearSelection": "Clear selection",
    "ecosystem.subCompanies": "sub-companies",
    "ecosystem.addSubCompany": "Add sub-company",
    "ecosystem.unlinkedSatellites": "Unlinked satellites",
    "ecosystem.noCompanies": "No companies yet",
    "settings.accounts": "Accounts",
    "settings.expenseCategories": "Expense Cat.",
    "settings.incomeCategories": "Income Cat.",
    "settings.incomeTypes": "Income Types",
    "settings.addItem": "Add",
    "settings.noItems": "No items registered",
    "settings.actions": "Actions",
    "priority.critical": "Critical",
    "priority.high": "High",
    "priority.medium": "Medium",
    "priority.low": "Low",
    "home.summary": "Here's your business ecosystem summary",
    "home.monthlyIncome": "Monthly Income",
    "home.monthlyExpenses": "Monthly Expenses",
    "home.monthlyBalance": "Monthly Balance",
    "home.ecosystemLinks": "Ecosystem Links",
    "home.companies": "Companies",
    "home.companiesRegistered": "companies registered",
    "home.documents": "Documents",
    "home.documentsSaved": "documents saved",
    "home.godModeActive": "God Mode Active",
    "home.godModeDesc": "Your second mind is ready. Control everything by voice or text.",
    "home.activate": "Activate",
    "home.aiAssistant": "AI Assistant",
    "home.tipTitle": "God Mode Tip",
    "home.tipDesc": "Try saying \"Show my financial summary\" or \"What are my most important links?\" in God Mode for quick insights.",
    "home.quickActions": "Quick Actions",
    "home.profitLoss": "Profit & Loss",
    "home.netIncome": "Net Income",
    "home.consolidatedView": "Consolidated View",
    "money.importStatement": "Import Statement",
    "money.importBankStatement": "Import Bank Statement",
    "money.selectFile": "Select File",
    "money.dropOrClick": "Drop file here or click to upload",
    "money.transactions": "transactions",
    "money.changeFile": "Change file",
    "money.defaultSource": "Default Source",
    "money.defaultCategory": "Default Category",
    "money.import": "Import",
    "money.transactionsImported": "transactions imported",
    "money.errorParseFile": "Error parsing file",
    "money.selectTransactions": "Select at least one transaction",
    "money.errorImport": "Error importing transactions",
    "common.date": "Date",
    "common.description": "Description",
    "documents.title": "Documents",
    "documents.saved": "documents saved",
    "documents.search": "Search documents...",
    "documents.category": "Category",
    "documents.all": "All",
    "documents.add": "Add",
    "documents.addDocument": "Add Document",
    "documents.upload": "Upload",
    "documents.link": "Link",
    "documents.name": "Name",
    "documents.fileUrl": "File URL",
    "documents.noDocuments": "No documents found",
    "documents.clickToAdd": "Click \"Add\" to create your first document",
    "documents.noDocCategory": "No documents",
    "documents.contracts": "Contracts",
    "documents.invoices": "Invoices",
    "documents.receipts": "Receipts",
    "documents.legal": "Legal Documents",
    "documents.financial": "Financial",
    "documents.other": "Other",
    "documents.categories": "Categories",
    "documents.manageCategories": "Manage Categories",
    "documents.newCategoryName": "New category name",
    "documents.customCategories": "Custom Categories",
    "documents.noCustomCategories": "No custom categories. Create one above!",
    "documents.defaultCategories": "Default Categories",
    "documents.categoryExists": "Category already exists",
    "documents.categoryAdded": "Category added!",
    "settings.selectCompany": "Edit Company",
    "settings.globalSettings": "Global Settings",
    "assistant.hello": "Hello!",
    "assistant.howCanHelp": "How can I help you today?",
    "assistant.listening": "Listening... speak naturally",
    "assistant.reviewSend": "Review and press Enter or click send",
    "assistant.typeOrMic": "Type or click the mic...",
    "assistant.speechHere": "Your speech will appear here...",
    "toast.companyUpdated": "Company updated!",
    "toast.companyCreated": "Company created!",
    "toast.errorSaving": "Error saving",
    "toast.fillRequired": "Please fill all required fields",
    "toast.linkAdded": "Link added!",
    "toast.errorAdding": "Error adding",
    "toast.linkRemoved": "Link removed!",
    "toast.errorRemoving": "Error removing",
    "toast.companyRemoved": "Company removed!",
    "common.optional": "optional",
    "company.type": "Type",
    "company.mainCompany": "Main Company",
    "company.subsidiary": "Subsidiary/Related",
    "company.parentCompany": "Parent Company",
    "company.selectParent": "Select parent company...",
    "company.name": "Company Name",
    "company.satellite": "Satellite",
    "company.about": "About",
    "company.aboutPlaceholder": "Describe your company, mission, and services...",
    "company.logoUrl": "Logo URL",
    "company.overview": "Overview",
    "company.manage": "Manage",
    "company.tips": "Tips",
    "company.employees": "Employees",
    "company.clients": "Clients",
    "company.providers": "Providers",
    "company.aboutTitle": "About Company",
    "company.noDescription": "No description added yet. Click edit to add one.",
    "company.active": "Active",
    "company.tipsTitle": "Getting Started",
    "company.tipsDesc": "Here are some tips to help you manage your company effectively.",
    "company.tipEmployees": "Add employees to track your team members, their roles, and hourly rates.",
    "company.tipClients": "Register clients to manage your customer relationships and contacts.",
    "company.tipDocuments": "Upload important documents like contracts, invoices, and receipts.",
    "company.tipFinances": "Set up income sources and expense categories to track your finances.",
    "company.quickActions": "Quick Actions",
    "company.addEmployee": "+ Employee",
    "company.addClient": "+ Client",
    "company.addDocument": "+ Document",
    "company.websiteUrl": "Website",
    "company.contactEmail": "Email",
    "company.contactPhone": "Phone",
    "company.socialLinks": "Social Links",
    "company.services": "Services",
    "company.servicesPlaceholder": "List your main services...",
    "company.coverImage": "Cover Image",
    "company.changeCover": "Change Cover",
    "company.imageUploaded": "Image uploaded successfully!",
    "company.uploadError": "Error uploading image",
    "company.fileTooLarge": "File too large (max 5MB)",
    "company.mission": "Mission",
    "company.missionPlaceholder": "What is your company's mission?",
    "company.portfolio": "Portfolio",
    "company.manageLinks": "Manage Links",
    "company.noLinks": "No links registered",
    "company.addLinkHint": "Add useful links for your company",
    "company.addLink": "Add Link",
    "company.linkCategory": "Category",
    "company.linkName": "Name",
    "company.linkUrl": "URL",
    "company.linkNameUrlRequired": "Name and URL are required",
    "company.linkAdded": "Link added!",
    "company.linkUpdated": "Link updated!",
    "company.linkDeleted": "Link removed!",
    "company.linkError": "Error saving link",
    "admin.tenants": "Admin - Tenants",
    "admin.tenantsDesc": "Manage all platform clients/tenants",
    "admin.newTenant": "New Tenant",
    "admin.searchTenants": "Search by name, slug or email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.tenant": "Tenant",
    "admin.domain": "Domain",
    "admin.owner": "Owner",
    "admin.status": "Status",
    "admin.share": "Share",
    "admin.actions": "Actions",
    "admin.noTenantFound": "No tenant found",
    "admin.noTenantRegistered": "No tenant registered",
    "admin.activeStatus": "Active",
    "admin.inactiveStatus": "Inactive",
    "admin.copyLink": "Copy link",
    "admin.sendWhatsApp": "Send via WhatsApp",
    "admin.sendEmail": "Send via Email",
    "admin.generatePDF": "Generate PDF",
    "admin.remixGuide": "Remix Guide",
    "admin.editTenant": "Edit Tenant",
    "admin.createTenant": "Create Tenant",
    "admin.updateInfo": "Update tenant information",
    "admin.fillData": "Fill in the data to create a new tenant",
    "admin.name": "Name",
    "admin.slug": "Slug",
    "admin.customDomain": "Custom Domain",
    "admin.ownerName": "Owner Name",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Phone (WhatsApp)",
    "admin.businessType": "Business Type",
    "admin.primaryColor": "Primary Color",
    "admin.logoUrl": "Logo URL",
    "admin.requiredFields": "Name and slug are required",
    "admin.tenantUpdated": "Tenant updated!",
    "admin.tenantCreated": "Tenant created!",
    "admin.slugExists": "Slug or domain already exists",
    "admin.errorSaving": "Error saving tenant",
    "admin.confirmDelete": "Confirm Deletion",
    "admin.deleteWarning": "Are you sure you want to delete this tenant? This action cannot be undone and all associated data will be lost.",
    "admin.tenantRemoved": "Tenant removed!",
    "admin.errorDeleting": "Error deleting tenant",
    "admin.tenantActivated": "Tenant activated",
    "admin.tenantDeactivated": "Tenant deactivated",
    "admin.errorUpdating": "Error updating tenant",
    "admin.errorLoading": "Error loading tenants",
    "admin.accessDenied": "Access denied. Only super admins can access this page.",
    "admin.linkCopied": "Link copied!",
    "admin.remixGuideTitle": "Remix Guide",
    "admin.remixGuideDesc": "Follow the steps below to create an isolated project for this client",
    "admin.clientData": "CLIENT DATA",
    "admin.stepByStep": "STEP BY STEP",
    "admin.step1Title": "Remix the Project",
    "admin.step1Desc": "Click on project name → Settings → Remix",
    "admin.step2Title": "Activate Lovable Cloud",
    "admin.step2Desc": "In the new project, activate Cloud for isolated database",
    "admin.step3Title": "Customize",
    "admin.step3Desc": "Change colors and add logo if needed",
    "admin.step4Title": "Configure Domain",
    "admin.step4Desc": "Settings → Domains → Add",
    "admin.step5Title": "Transfer to Client",
    "admin.step5Desc": "Settings → Transfer → Send to",
    "admin.copyChecklist": "Copy Checklist",
    "admin.close": "Close",
    "admin.infoCopied": "Information copied!",
    "admin.cleaning": "Cleaning",
    "admin.restaurant": "Restaurant",
    "admin.construction": "Construction",
    "admin.retail": "Retail",
    "admin.tech": "Technology",
    "admin.health": "Health",
    "admin.education": "Education",
    "admin.other": "Other",
  },
  "fr-CA": {
    "nav.home": "Accueil",
    "nav.assistant": "Assistant",
    "nav.documents": "Documents",
    "nav.money": "Finances",
    "nav.companies": "Écosystème",
    "nav.settings": "Paramètres",
    "nav.help": "Aide",
    "settings.subtitle": "Personnalisez votre app et configurez votre entreprise",
    "settings.branding": "Image de marque",
    "settings.brandingDesc": "Configurez le nom, le logo et les informations de votre entreprise",
    "settings.preferences": "Préférences",
    "settings.preferencesDesc": "Langue, devise et autres préférences système",
    "settings.setup": "Configuration Initiale",
    "settings.setupDesc": "Refaites l'assistant de configuration pour mettre à jour votre type d'entreprise",
    "settings.saved": "Paramètres enregistrés!",
    "settings.companyLogo": "Logo de l'entreprise",
    "settings.logoHint": "PNG, JPG jusqu'à 2MB",
    "settings.logoPlaceholder": "URL du logo (ex: https://...)",
    "settings.companyName": "Nom de l'entreprise",
    "settings.businessType": "Type d'entreprise",
    "settings.selectPlaceholder": "Sélectionnez...",
    "settings.ownerName": "Nom du propriétaire",
    "settings.email": "Email",
    "settings.phone": "Téléphone",
    "settings.address": "Adresse",
    "settings.language": "Langue",
    "settings.currency": "Devise",
    "settings.redoSetup": "Refaire la configuration initiale",
    "settings.saveChanges": "Sauvegarder les modifications",
    "settings.confirmRedo": "Refaire la configuration?",
    "settings.confirmRedoDesc": "Vous êtes sur le point de refaire la configuration initiale. Les liens existants seront conservés, mais de nouveaux liens seront ajoutés selon le nouveau type d'entreprise.",
    "settings.continue": "Continuer",
    "settings.errorSaving": "Erreur lors de la sauvegarde",
    "common.add": "Ajouter",
    "common.save": "Sauvegarder",
    "common.cancel": "Annuler",
    "common.delete": "Supprimer",
    "common.edit": "Modifier",
    "common.search": "Rechercher",
    "common.loading": "Chargement...",
    "common.noResults": "Aucun résultat",
    "common.export": "Exporter",
    "common.total": "Total",
    "common.result": "Résultat",
    "common.settings": "Paramètres",
    "common.report": "Rapport",
    "common.logout": "Déconnexion",
    "common.viewAll": "Voir tout",
    "common.clearHistory": "Effacer l'historique",
    "common.newConversation": "Nouvelle conversation",
    "money.title": "Contrôle Financier",
    "money.subtitle": "Contrôle financier complet",
    "money.income": "Revenus",
    "money.incomeTotal": "Revenus Totaux",
    "money.expenses": "Dépenses",
    "money.expensesTotal": "Dépenses Totales",
    "money.sources": "Sources de Revenus",
    "money.sourcesDesc": "Gérez vos sources de revenus",
    "money.categoriesDesc": "Gérer les dépenses par catégorie",
    "money.addSource": "Source",
    "money.addCategory": "Catégorie",
    "money.newSource": "Nouvelle Source",
    "money.newCategory": "Nouvelle Catégorie",
    "money.taxPercent": "Taxe (%)",
    "money.noSources": "Aucune source. Cliquez sur Source pour ajouter.",
    "money.noCategories": "Aucune catégorie. Cliquez sur Catégorie pour ajouter.",
    "money.annualReport": "Résumé Annuel",
    "money.reportDesc": "Vue financière consolidée",
    "money.settingsTitle": "Paramètres Financiers",
    "money.settingsDesc": "Gérer les sources et catégories",
    "money.sourceAdded": "Source ajoutée!",
    "money.categoryAdded": "Catégorie ajoutée!",
    "money.errorAddSource": "Erreur lors de l'ajout de la source",
    "money.errorAddCategory": "Erreur lors de l'ajout de la catégorie",
    "money.errorLoadData": "Erreur lors du chargement des données",
    "money.errorUpdateValue": "Erreur lors de la mise à jour de la valeur",
    "money.addTransaction": "Ajouter Transaction",
    "money.selectSource": "Sélectionner source...",
    "money.selectCategory": "Sélectionner catégorie...",
    "money.sourceName": "Nom de la source",
    "money.categoryName": "Nom de la catégorie",
    "money.amount": "Montant",
    "money.month": "Mois",
    "money.addIncome": "Ajouter Revenu",
    "money.addExpense": "Ajouter Dépense",
    "money.notesPlaceholder": "Notes additionnelles...",
    "money.scanReceipt": "Scanner Reçu",
    "money.takePhoto": "Prendre Photo",
    "money.uploadImage": "Télécharger Image",
    "money.analyzing": "Analyse en cours...",
    "money.extractedData": "Données Extraites",
    "money.receiptAnalyzed": "Reçu analysé avec succès!",
    "money.errorAnalyzing": "Erreur lors de l'analyse",
    "money.fileTooLarge": "Fichier trop volumineux (max 4MB)",
    "money.errorProcessing": "Erreur de traitement de l'image",
    "money.merchant": "Commerçant",
    "money.type": "Type",
    "money.category": "Catégorie",
    "money.date": "Date",
    "money.retry": "Réessayer",
    "money.useData": "Utiliser Ces Données",
    "money.scanReceiptDesc": "Prenez une photo ou téléchargez une image de votre reçu",
    "money.noSourcesHint": "Aucune source. Créez-en une ci-dessous:",
    "money.noCategoriesHint": "Aucune catégorie. Créez-en une ci-dessous:",
    "common.notes": "Notes",
    "ecosystem.title": "Écosystème Hub",
    "ecosystem.name": "Nom",
    "ecosystem.noLinks": "Aucun lien dans cette catégorie",
    "ecosystem.companies": "Entreprises",
    "ecosystem.links": "Liens",
    "ecosystem.allCompanies": "Toutes les entreprises",
    "ecosystem.clearSelection": "Effacer la sélection",
    "ecosystem.subCompanies": "sous-entreprises",
    "ecosystem.addSubCompany": "Ajouter sous-entreprise",
    "ecosystem.unlinkedSatellites": "Satellites non liés",
    "ecosystem.noCompanies": "Aucune entreprise",
    "settings.accounts": "Comptes",
    "settings.expenseCategories": "Cat. Dépenses",
    "settings.incomeCategories": "Cat. Revenus",
    "settings.incomeTypes": "Types Revenus",
    "settings.addItem": "Ajouter",
    "settings.noItems": "Aucun élément enregistré",
    "settings.actions": "Actions",
    "priority.critical": "Critique",
    "priority.high": "Élevé",
    "priority.medium": "Moyen",
    "priority.low": "Faible",
    "home.summary": "Voici le résumé de votre écosystème d'affaires",
    "home.monthlyIncome": "Revenus du mois",
    "home.monthlyExpenses": "Dépenses du mois",
    "home.monthlyBalance": "Solde du mois",
    "home.ecosystemLinks": "Liens Écosystème",
    "home.companies": "Entreprises",
    "home.companiesRegistered": "entreprises enregistrées",
    "home.documents": "Documents",
    "home.documentsSaved": "documents sauvegardés",
    "home.godModeActive": "God Mode Actif",
    "home.godModeDesc": "Votre deuxième esprit est prêt. Contrôlez tout par voix ou texte.",
    "home.activate": "Activer",
    "home.aiAssistant": "Assistant IA",
    "home.tipTitle": "Conseil God Mode",
    "home.tipDesc": "Essayez de dire \"Montre mon résumé financier\" ou \"Quels sont mes liens les plus importants?\" dans God Mode.",
    "home.quickActions": "Actions Rapides",
    "home.profitLoss": "Profit & Perte",
    "home.netIncome": "Bénéfice Net",
    "home.consolidatedView": "Vue Consolidée",
    "money.importStatement": "Importer Relevé",
    "money.importBankStatement": "Importer Relevé Bancaire",
    "money.selectFile": "Sélectionner un fichier",
    "money.dropOrClick": "Déposez ici ou cliquez pour téléverser",
    "money.transactions": "transactions",
    "money.changeFile": "Changer de fichier",
    "money.defaultSource": "Source par défaut",
    "money.defaultCategory": "Catégorie par défaut",
    "money.import": "Importer",
    "money.transactionsImported": "transactions importées",
    "money.errorParseFile": "Erreur d'analyse du fichier",
    "money.selectTransactions": "Sélectionnez au moins une transaction",
    "money.errorImport": "Erreur lors de l'importation",
    "common.date": "Date",
    "common.description": "Description",
    "documents.title": "Documents",
    "documents.saved": "documents sauvegardés",
    "documents.search": "Rechercher documents...",
    "documents.category": "Catégorie",
    "documents.all": "Toutes",
    "documents.add": "Ajouter",
    "documents.addDocument": "Ajouter Document",
    "documents.upload": "Télécharger",
    "documents.link": "Lien",
    "documents.name": "Nom",
    "documents.fileUrl": "URL du fichier",
    "documents.noDocuments": "Aucun document trouvé",
    "documents.clickToAdd": "Cliquez sur \"Ajouter\" pour créer votre premier document",
    "documents.noDocCategory": "Aucun document",
    "documents.contracts": "Contrats",
    "documents.invoices": "Factures",
    "documents.receipts": "Reçus",
    "documents.legal": "Documents Légaux",
    "documents.financial": "Financier",
    "documents.other": "Autre",
    "documents.categories": "Catégories",
    "documents.manageCategories": "Gérer les Catégories",
    "documents.newCategoryName": "Nom de la nouvelle catégorie",
    "documents.customCategories": "Catégories Personnalisées",
    "documents.noCustomCategories": "Aucune catégorie personnalisée. Créez-en une ci-dessus!",
    "documents.defaultCategories": "Catégories par défaut",
    "documents.categoryExists": "La catégorie existe déjà",
    "documents.categoryAdded": "Catégorie ajoutée!",
    "settings.selectCompany": "Modifier l'Entreprise",
    "settings.globalSettings": "Paramètres Globaux",
    "assistant.hello": "Bonjour!",
    "assistant.howCanHelp": "Comment puis-je vous aider aujourd'hui?",
    "assistant.listening": "Écoute... parlez naturellement",
    "assistant.reviewSend": "Révisez et appuyez sur Entrée ou cliquez sur envoyer",
    "assistant.typeOrMic": "Tapez ou cliquez sur le micro...",
    "assistant.speechHere": "Votre parole apparaîtra ici...",
    "toast.companyUpdated": "Entreprise mise à jour!",
    "toast.companyCreated": "Entreprise créée!",
    "toast.errorSaving": "Erreur lors de la sauvegarde",
    "toast.fillRequired": "Veuillez remplir tous les champs obligatoires",
    "toast.linkAdded": "Lien ajouté!",
    "toast.errorAdding": "Erreur lors de l'ajout",
    "toast.linkRemoved": "Lien supprimé!",
    "toast.errorRemoving": "Erreur lors de la suppression",
    "toast.companyRemoved": "Entreprise supprimée!",
    "common.optional": "optionnel",
    "company.type": "Type",
    "company.mainCompany": "Entreprise principale",
    "company.subsidiary": "Filiale/Associée",
    "company.parentCompany": "Entreprise mère",
    "company.selectParent": "Sélectionner l'entreprise mère...",
    "company.name": "Nom de l'entreprise",
    "company.satellite": "Satellite",
    "company.about": "À propos",
    "company.aboutPlaceholder": "Décrivez votre entreprise, mission et services...",
    "company.logoUrl": "URL du logo",
    "company.overview": "Aperçu",
    "company.manage": "Gérer",
    "company.tips": "Conseils",
    "company.employees": "Employés",
    "company.clients": "Clients",
    "company.providers": "Fournisseurs",
    "company.aboutTitle": "À propos",
    "company.noDescription": "Aucune description. Cliquez sur modifier pour en ajouter une.",
    "company.active": "Actif",
    "company.tipsTitle": "Pour commencer",
    "company.tipsDesc": "Voici quelques conseils pour gérer efficacement votre entreprise.",
    "company.tipEmployees": "Ajoutez des employés pour suivre les membres de votre équipe et leurs taux horaires.",
    "company.tipClients": "Enregistrez des clients pour gérer vos relations et contacts.",
    "company.tipDocuments": "Téléchargez des documents importants comme contrats et factures.",
    "company.tipFinances": "Configurez les sources de revenus et catégories de dépenses.",
    "company.quickActions": "Actions rapides",
    "company.addEmployee": "+ Employé",
    "company.addClient": "+ Client",
    "company.addDocument": "+ Document",
    "company.websiteUrl": "Site Web",
    "company.contactEmail": "Email",
    "company.contactPhone": "Téléphone",
    "company.socialLinks": "Liens Sociaux",
    "company.services": "Services",
    "company.servicesPlaceholder": "Listez vos services principaux...",
    "company.coverImage": "Image de couverture",
    "company.changeCover": "Changer la couverture",
    "company.imageUploaded": "Image téléchargée avec succès!",
    "company.uploadError": "Erreur lors du téléchargement",
    "company.fileTooLarge": "Fichier trop volumineux (max 5Mo)",
    "company.mission": "Mission",
    "company.missionPlaceholder": "Quelle est la mission de votre entreprise?",
    "company.portfolio": "Portfolio",
    "company.manageLinks": "Gérer les liens",
    "company.noLinks": "Aucun lien enregistré",
    "company.addLinkHint": "Ajoutez des liens utiles pour votre entreprise",
    "company.addLink": "Ajouter un lien",
    "company.linkCategory": "Catégorie",
    "company.linkName": "Nom",
    "company.linkUrl": "URL",
    "company.linkNameUrlRequired": "Nom et URL sont requis",
    "company.linkAdded": "Lien ajouté!",
    "company.linkUpdated": "Lien mis à jour!",
    "company.linkDeleted": "Lien supprimé!",
    "company.linkError": "Erreur lors de l'enregistrement",
    "admin.tenants": "Admin - Clients",
    "admin.tenantsDesc": "Gérez tous les clients/tenants de la plateforme",
    "admin.newTenant": "Nouveau Tenant",
    "admin.searchTenants": "Rechercher par nom, slug ou email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Actifs",
    "admin.inactive": "Inactifs",
    "admin.tenant": "Tenant",
    "admin.domain": "Domaine",
    "admin.owner": "Propriétaire",
    "admin.status": "Statut",
    "admin.share": "Partager",
    "admin.actions": "Actions",
    "admin.noTenantFound": "Aucun tenant trouvé",
    "admin.noTenantRegistered": "Aucun tenant enregistré",
    "admin.activeStatus": "Actif",
    "admin.inactiveStatus": "Inactif",
    "admin.copyLink": "Copier le lien",
    "admin.sendWhatsApp": "Envoyer par WhatsApp",
    "admin.sendEmail": "Envoyer par Email",
    "admin.generatePDF": "Générer PDF",
    "admin.remixGuide": "Guide Remix",
    "admin.editTenant": "Modifier Tenant",
    "admin.createTenant": "Créer Tenant",
    "admin.updateInfo": "Mettre à jour les informations",
    "admin.fillData": "Remplissez les données pour créer un nouveau tenant",
    "admin.name": "Nom",
    "admin.slug": "Slug",
    "admin.customDomain": "Domaine personnalisé",
    "admin.ownerName": "Nom du propriétaire",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Téléphone (WhatsApp)",
    "admin.businessType": "Type d'entreprise",
    "admin.primaryColor": "Couleur principale",
    "admin.logoUrl": "URL du logo",
    "admin.requiredFields": "Nom et slug sont obligatoires",
    "admin.tenantUpdated": "Tenant mis à jour!",
    "admin.tenantCreated": "Tenant créé!",
    "admin.slugExists": "Slug ou domaine existe déjà",
    "admin.errorSaving": "Erreur lors de la sauvegarde",
    "admin.confirmDelete": "Confirmer la suppression",
    "admin.deleteWarning": "Êtes-vous sûr de vouloir supprimer ce tenant? Cette action est irréversible.",
    "admin.tenantRemoved": "Tenant supprimé!",
    "admin.errorDeleting": "Erreur lors de la suppression",
    "admin.tenantActivated": "Tenant activé",
    "admin.tenantDeactivated": "Tenant désactivé",
    "admin.errorUpdating": "Erreur lors de la mise à jour",
    "admin.errorLoading": "Erreur lors du chargement",
    "admin.accessDenied": "Accès refusé. Seuls les super admins peuvent accéder.",
    "admin.linkCopied": "Lien copié!",
    "admin.remixGuideTitle": "Guide Remix",
    "admin.remixGuideDesc": "Suivez les étapes ci-dessous pour créer un projet isolé",
    "admin.clientData": "DONNÉES CLIENT",
    "admin.stepByStep": "ÉTAPE PAR ÉTAPE",
    "admin.step1Title": "Remix le Projet",
    "admin.step1Desc": "Cliquez sur le nom du projet → Settings → Remix",
    "admin.step2Title": "Activer Lovable Cloud",
    "admin.step2Desc": "Dans le nouveau projet, activez Cloud pour BD isolée",
    "admin.step3Title": "Personnaliser",
    "admin.step3Desc": "Modifiez les couleurs et ajoutez le logo",
    "admin.step4Title": "Configurer Domaine",
    "admin.step4Desc": "Settings → Domains → Ajouter",
    "admin.step5Title": "Transférer au Client",
    "admin.step5Desc": "Settings → Transfer → Envoyer à",
    "admin.copyChecklist": "Copier Checklist",
    "admin.close": "Fermer",
    "admin.infoCopied": "Informations copiées!",
    "admin.cleaning": "Nettoyage",
    "admin.restaurant": "Restaurant",
    "admin.construction": "Construction",
    "admin.retail": "Commerce",
    "admin.tech": "Technologie",
    "admin.health": "Santé",
    "admin.education": "Éducation",
    "admin.other": "Autre",
  },
  "pt-BR": {
    "nav.home": "Início",
    "nav.assistant": "Assistente",
    "nav.documents": "Documentos",
    "nav.money": "Dinheiro",
    "nav.companies": "Empresas",
    "nav.settings": "Config",
    "nav.help": "Ajuda",
    "settings.subtitle": "Personalize seu app e configure seu negócio",
    "settings.branding": "Branding & Identidade",
    "settings.brandingDesc": "Configure o nome, logo e informações da sua empresa",
    "settings.preferences": "Preferências",
    "settings.preferencesDesc": "Idioma, moeda e outras preferências do sistema",
    "settings.setup": "Configuração Inicial",
    "settings.setupDesc": "Refaça o assistente de configuração para atualizar seu tipo de negócio",
    "settings.saved": "Configurações salvas com sucesso!",
    "settings.companyLogo": "Logo da Empresa",
    "settings.logoHint": "PNG, JPG até 2MB",
    "settings.logoPlaceholder": "URL do logo (ex: https://...)",
    "settings.companyName": "Nome da Empresa",
    "settings.businessType": "Tipo de Negócio",
    "settings.selectPlaceholder": "Selecione...",
    "settings.ownerName": "Nome do Proprietário",
    "settings.email": "Email",
    "settings.phone": "Telefone",
    "settings.address": "Endereço",
    "settings.language": "Idioma",
    "settings.currency": "Moeda",
    "settings.redoSetup": "Refazer Setup Inicial",
    "settings.saveChanges": "Salvar Alterações",
    "settings.confirmRedo": "Refazer Configuração?",
    "settings.confirmRedoDesc": "Você está prestes a refazer o setup inicial. Os links existentes serão mantidos, mas novos links serão adicionados baseados no novo tipo de negócio selecionado.",
    "settings.continue": "Continuar",
    "settings.errorSaving": "Erro ao salvar configurações",
    "common.add": "Adicionar",
    "common.save": "Salvar",
    "common.cancel": "Cancelar",
    "common.delete": "Excluir",
    "common.edit": "Editar",
    "common.search": "Buscar",
    "common.loading": "Carregando...",
    "common.noResults": "Nenhum resultado",
    "common.export": "Exportar",
    "common.total": "Total",
    "common.result": "Resultado",
    "common.settings": "Config",
    "common.report": "Relatório",
    "common.logout": "Sair",
    "common.viewAll": "Ver todos",
    "common.clearHistory": "Limpar histórico",
    "common.newConversation": "Nova conversa",
    "money.title": "Controle Financeiro",
    "money.subtitle": "Controle financeiro completo",
    "money.income": "Receitas",
    "money.incomeTotal": "Receita Total",
    "money.expenses": "Despesas",
    "money.expensesTotal": "Despesas Totais",
    "money.sources": "Fontes de Receita",
    "money.sourcesDesc": "Gerencie suas fontes de renda",
    "money.categoriesDesc": "Gerencie seus gastos por categoria",
    "money.addSource": "Fonte",
    "money.addCategory": "Categoria",
    "money.newSource": "Nova Fonte de Receita",
    "money.newCategory": "Nova Categoria",
    "money.taxPercent": "Imposto (%)",
    "money.noSources": "Nenhuma fonte cadastrada. Clique em Fonte para adicionar.",
    "money.noCategories": "Nenhuma categoria cadastrada. Clique em Categoria para adicionar.",
    "money.annualReport": "Resumo Anual",
    "money.reportDesc": "Visão consolidada das finanças",
    "money.settingsTitle": "Configurações Financeiras",
    "money.settingsDesc": "Gerencie fontes e categorias",
    "money.sourceAdded": "Fonte adicionada!",
    "money.categoryAdded": "Categoria adicionada!",
    "money.errorAddSource": "Erro ao adicionar fonte",
    "money.errorAddCategory": "Erro ao adicionar categoria",
    "money.errorLoadData": "Erro ao carregar dados",
    "money.errorUpdateValue": "Erro ao atualizar valor",
    "money.addTransaction": "Adicionar Transação",
    "money.selectSource": "Selecionar fonte...",
    "money.selectCategory": "Selecionar categoria...",
    "money.sourceName": "Nome da fonte",
    "money.categoryName": "Nome da categoria",
    "money.amount": "Valor",
    "money.month": "Mês",
    "money.addIncome": "Adicionar Receita",
    "money.addExpense": "Adicionar Despesa",
    "money.notesPlaceholder": "Observações...",
    "money.scanReceipt": "Escanear Recibo",
    "money.takePhoto": "Tirar Foto",
    "money.uploadImage": "Enviar Imagem",
    "money.analyzing": "Analisando...",
    "money.extractedData": "Dados Extraídos",
    "money.receiptAnalyzed": "Recibo analisado com sucesso!",
    "money.errorAnalyzing": "Erro ao analisar recibo",
    "money.fileTooLarge": "Arquivo muito grande (max 4MB)",
    "money.errorProcessing": "Erro ao processar imagem",
    "money.merchant": "Estabelecimento",
    "money.type": "Tipo",
    "money.category": "Categoria",
    "money.date": "Data",
    "money.retry": "Tentar Novamente",
    "money.useData": "Usar Esses Dados",
    "money.scanReceiptDesc": "Tire uma foto ou envie uma imagem do seu recibo",
    "money.noSourcesHint": "Nenhuma fonte. Crie uma abaixo:",
    "money.noCategoriesHint": "Nenhuma categoria. Crie uma abaixo:",
    "common.notes": "Notas",
    "ecosystem.title": "Ecossistema Hub",
    "ecosystem.name": "Nome",
    "ecosystem.noLinks": "Nenhum link nesta categoria",
    "ecosystem.companies": "Empresas",
    "ecosystem.links": "Links",
    "ecosystem.allCompanies": "Todas as empresas",
    "ecosystem.clearSelection": "Limpar seleção",
    "ecosystem.subCompanies": "sub-empresas",
    "ecosystem.addSubCompany": "Adicionar sub-empresa",
    "ecosystem.unlinkedSatellites": "Satélites não vinculados",
    "ecosystem.noCompanies": "Nenhuma empresa ainda",
    "settings.accounts": "Contas",
    "settings.expenseCategories": "Cat. Despesas",
    "settings.incomeCategories": "Cat. Receitas",
    "settings.incomeTypes": "Tipos Receita",
    "settings.addItem": "Adicionar",
    "settings.noItems": "Nenhum item cadastrado",
    "settings.actions": "Ações",
    "priority.critical": "Crítico",
    "priority.high": "Alto",
    "priority.medium": "Médio",
    "priority.low": "Baixo",
    "home.summary": "Aqui está o resumo do seu ecossistema empresarial",
    "home.monthlyIncome": "Receita do mês",
    "home.monthlyExpenses": "Despesas do mês",
    "home.monthlyBalance": "Saldo do mês",
    "home.ecosystemLinks": "Links no Ecosystem",
    "home.companies": "Empresas",
    "home.companiesRegistered": "empresas cadastradas",
    "home.documents": "Documentos",
    "home.documentsSaved": "documentos salvos",
    "home.godModeActive": "God Mode Ativo",
    "home.godModeDesc": "Sua segunda mente está pronta. Controle tudo por voz ou texto.",
    "home.activate": "Ativar",
    "home.aiAssistant": "Inteligência Artificial",
    "home.tipTitle": "Dica do God Mode",
    "home.tipDesc": "Experimente dizer \"Mostre meu resumo financeiro\" ou \"Quais são meus links mais importantes?\" no God Mode para obter insights rápidos.",
    "home.quickActions": "Ações Rápidas",
    "home.profitLoss": "Lucros e Perdas",
    "home.netIncome": "Lucro Líquido",
    "home.consolidatedView": "Visão Consolidada",
    "money.importStatement": "Importar Extrato",
    "money.importBankStatement": "Importar Extrato Bancário",
    "money.selectFile": "Selecionar Arquivo",
    "money.dropOrClick": "Arraste aqui ou clique para enviar",
    "money.transactions": "transações",
    "money.changeFile": "Trocar arquivo",
    "money.defaultSource": "Fonte Padrão",
    "money.defaultCategory": "Categoria Padrão",
    "money.import": "Importar",
    "money.transactionsImported": "transações importadas",
    "money.errorParseFile": "Erro ao analisar arquivo",
    "money.selectTransactions": "Selecione pelo menos uma transação",
    "money.errorImport": "Erro ao importar transações",
    "common.date": "Data",
    "common.description": "Descrição",
    "documents.title": "Documentos",
    "documents.saved": "documentos salvos",
    "documents.search": "Buscar documentos...",
    "documents.category": "Categoria",
    "documents.all": "Todas",
    "documents.add": "Adicionar",
    "documents.addDocument": "Adicionar Documento",
    "documents.upload": "Upload",
    "documents.link": "Link",
    "documents.name": "Nome",
    "documents.fileUrl": "URL do arquivo",
    "documents.noDocuments": "Nenhum documento encontrado",
    "documents.clickToAdd": "Clique em \"Adicionar\" para criar seu primeiro documento",
    "documents.noDocCategory": "Nenhum documento",
    "documents.contracts": "Contratos",
    "documents.invoices": "Notas Fiscais",
    "documents.receipts": "Recibos",
    "documents.legal": "Documentos Legais",
    "documents.financial": "Financeiro",
    "documents.other": "Outros",
    "documents.categories": "Categorias",
    "documents.manageCategories": "Gerenciar Categorias",
    "documents.newCategoryName": "Nome da nova categoria",
    "documents.customCategories": "Categorias Personalizadas",
    "documents.noCustomCategories": "Sem categorias personalizadas. Crie uma acima!",
    "documents.defaultCategories": "Categorias Padrão",
    "documents.categoryExists": "Categoria já existe",
    "documents.categoryAdded": "Categoria adicionada!",
    "settings.selectCompany": "Editar Empresa",
    "settings.globalSettings": "Configurações Globais",
    "assistant.hello": "Olá!",
    "assistant.howCanHelp": "Como posso te ajudar hoje?",
    "assistant.listening": "Ouvindo... fale naturalmente",
    "assistant.reviewSend": "Revise e pressione Enter ou clique em enviar",
    "assistant.typeOrMic": "Digite ou clique no mic...",
    "assistant.speechHere": "Sua fala aparecerá aqui...",
    "toast.companyUpdated": "Empresa atualizada!",
    "toast.companyCreated": "Empresa criada!",
    "toast.errorSaving": "Erro ao salvar",
    "toast.fillRequired": "Preencha todos os campos obrigatórios",
    "toast.linkAdded": "Link adicionado!",
    "toast.errorAdding": "Erro ao adicionar",
    "toast.linkRemoved": "Link removido!",
    "toast.errorRemoving": "Erro ao remover",
    "toast.companyRemoved": "Empresa removida!",
    "common.optional": "opcional",
    "company.type": "Tipo",
    "company.mainCompany": "Empresa Principal",
    "company.subsidiary": "Filial/Relacionada",
    "company.parentCompany": "Empresa Mãe",
    "company.selectParent": "Selecionar empresa mãe...",
    "company.name": "Nome da Empresa",
    "company.satellite": "Satélite",
    "company.about": "Sobre",
    "company.aboutPlaceholder": "Descreva sua empresa, missão e serviços...",
    "company.logoUrl": "URL do Logo",
    "company.overview": "Visão Geral",
    "company.manage": "Gerenciar",
    "company.tips": "Dicas",
    "company.employees": "Funcionários",
    "company.clients": "Clientes",
    "company.providers": "Fornecedores",
    "company.aboutTitle": "Sobre a Empresa",
    "company.noDescription": "Sem descrição. Clique em editar para adicionar.",
    "company.active": "Ativo",
    "company.tipsTitle": "Primeiros Passos",
    "company.tipsDesc": "Aqui estão algumas dicas para gerenciar sua empresa de forma eficaz.",
    "company.tipEmployees": "Adicione funcionários para acompanhar sua equipe e seus valores por hora.",
    "company.tipClients": "Cadastre clientes para gerenciar seus relacionamentos e contatos.",
    "company.tipDocuments": "Faça upload de documentos importantes como contratos e notas fiscais.",
    "company.tipFinances": "Configure fontes de renda e categorias de despesas para suas finanças.",
    "company.quickActions": "Ações Rápidas",
    "company.addEmployee": "+ Funcionário",
    "company.addClient": "+ Cliente",
    "company.addDocument": "+ Documento",
    "company.websiteUrl": "Website",
    "company.contactEmail": "Email",
    "company.contactPhone": "Telefone",
    "company.socialLinks": "Links Sociais",
    "company.services": "Serviços",
    "company.servicesPlaceholder": "Liste seus principais serviços...",
    "company.coverImage": "Imagem de Capa",
    "company.changeCover": "Alterar Capa",
    "company.imageUploaded": "Imagem enviada com sucesso!",
    "company.uploadError": "Erro ao enviar imagem",
    "company.fileTooLarge": "Arquivo muito grande (máx 5MB)",
    "company.mission": "Missão",
    "company.missionPlaceholder": "Qual é a missão da sua empresa?",
    "company.portfolio": "Portfólio",
    "company.manageLinks": "Gerenciar Links",
    "company.noLinks": "Nenhum link cadastrado",
    "company.addLinkHint": "Adicione links úteis para sua empresa",
    "company.addLink": "Adicionar Link",
    "company.linkCategory": "Categoria",
    "company.linkName": "Nome",
    "company.linkUrl": "URL",
    "company.linkNameUrlRequired": "Nome e URL são obrigatórios",
    "company.linkAdded": "Link adicionado!",
    "company.linkUpdated": "Link atualizado!",
    "company.linkDeleted": "Link removido!",
    "company.linkError": "Erro ao salvar link",
    "admin.tenants": "Admin - Tenants",
    "admin.tenantsDesc": "Gerencie todos os clientes/tenants da plataforma",
    "admin.newTenant": "Novo Tenant",
    "admin.searchTenants": "Buscar por nome, slug ou email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Ativos",
    "admin.inactive": "Inativos",
    "admin.tenant": "Tenant",
    "admin.domain": "Domínio",
    "admin.owner": "Proprietário",
    "admin.status": "Status",
    "admin.share": "Compartilhar",
    "admin.actions": "Ações",
    "admin.noTenantFound": "Nenhum tenant encontrado",
    "admin.noTenantRegistered": "Nenhum tenant cadastrado",
    "admin.activeStatus": "Ativo",
    "admin.inactiveStatus": "Inativo",
    "admin.copyLink": "Copiar link",
    "admin.sendWhatsApp": "Enviar por WhatsApp",
    "admin.sendEmail": "Enviar por Email",
    "admin.generatePDF": "Gerar PDF",
    "admin.remixGuide": "Guia Remix",
    "admin.editTenant": "Editar Tenant",
    "admin.createTenant": "Criar Tenant",
    "admin.updateInfo": "Atualize as informações do tenant",
    "admin.fillData": "Preencha os dados para criar um novo tenant",
    "admin.name": "Nome",
    "admin.slug": "Slug",
    "admin.customDomain": "Domínio Personalizado",
    "admin.ownerName": "Nome do Proprietário",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Telefone (WhatsApp)",
    "admin.businessType": "Tipo de Negócio",
    "admin.primaryColor": "Cor Principal",
    "admin.logoUrl": "URL do Logo",
    "admin.requiredFields": "Nome e slug são obrigatórios",
    "admin.tenantUpdated": "Tenant atualizado!",
    "admin.tenantCreated": "Tenant criado!",
    "admin.slugExists": "Slug ou domínio já existe",
    "admin.errorSaving": "Erro ao salvar tenant",
    "admin.confirmDelete": "Confirmar Exclusão",
    "admin.deleteWarning": "Tem certeza que deseja excluir este tenant? Esta ação não pode ser desfeita e todos os dados associados serão perdidos.",
    "admin.tenantRemoved": "Tenant removido!",
    "admin.errorDeleting": "Erro ao remover tenant",
    "admin.tenantActivated": "Tenant ativado",
    "admin.tenantDeactivated": "Tenant desativado",
    "admin.errorUpdating": "Erro ao atualizar tenant",
    "admin.errorLoading": "Erro ao carregar tenants",
    "admin.accessDenied": "Acesso negado. Apenas super admins podem acessar esta página.",
    "admin.linkCopied": "Link copiado!",
    "admin.remixGuideTitle": "Guia de Remix",
    "admin.remixGuideDesc": "Siga os passos abaixo para criar um projeto isolado para este cliente",
    "admin.clientData": "DADOS DO CLIENTE",
    "admin.stepByStep": "PASSO A PASSO",
    "admin.step1Title": "Fazer Remix do Projeto",
    "admin.step1Desc": "Clique no nome do projeto → Settings → Remix",
    "admin.step2Title": "Ativar Lovable Cloud",
    "admin.step2Desc": "No novo projeto, ative o Cloud para banco isolado",
    "admin.step3Title": "Personalizar",
    "admin.step3Desc": "Altere cores e adicione logo se necessário",
    "admin.step4Title": "Configurar Domínio",
    "admin.step4Desc": "Settings → Domains → Adicionar",
    "admin.step5Title": "Transferir para Cliente",
    "admin.step5Desc": "Settings → Transfer → Enviar para",
    "admin.copyChecklist": "Copiar Checklist",
    "admin.close": "Fechar",
    "admin.infoCopied": "Informações copiadas!",
    "admin.cleaning": "Limpeza",
    "admin.restaurant": "Restaurante",
    "admin.construction": "Construção",
    "admin.retail": "Varejo",
    "admin.tech": "Tecnologia",
    "admin.health": "Saúde",
    "admin.education": "Educação",
    "admin.other": "Outro",
  },
  "en-US": {
    "nav.home": "Home",
    "nav.assistant": "Assistant",
    "nav.documents": "Documents",
    "nav.money": "Money",
    "nav.companies": "Ecosystem",
    "nav.settings": "Settings",
    "settings.subtitle": "Customize your app and set up your business",
    "settings.branding": "Branding & Identity",
    "settings.brandingDesc": "Set up your company name, logo and information",
    "settings.preferences": "Preferences",
    "settings.preferencesDesc": "Language, currency and other system preferences",
    "settings.setup": "Initial Setup",
    "settings.setupDesc": "Redo the setup wizard to update your business type and receive new suggested links",
    "settings.saved": "Settings saved successfully!",
    "common.add": "Add",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.search": "Search",
    "common.loading": "Loading...",
    "common.noResults": "No results found",
    "common.export": "Export",
    "common.total": "Total",
    "common.result": "Result",
    "common.settings": "Settings",
    "common.report": "Report",
    "common.logout": "Logout",
    "common.viewAll": "View all",
    "common.clearHistory": "Clear history",
    "common.newConversation": "New conversation",
    "money.title": "Financial Control",
    "money.subtitle": "Complete financial control",
    "money.income": "Income",
    "money.incomeTotal": "Total Income",
    "money.expenses": "Expenses",
    "money.expensesTotal": "Total Expenses",
    "money.sources": "Income Sources",
    "money.sourcesDesc": "Manage your income sources",
    "money.categoriesDesc": "Manage expenses by category",
    "money.addSource": "Source",
    "money.addCategory": "Category",
    "money.newSource": "New Income Source",
    "money.newCategory": "New Category",
    "money.taxPercent": "Tax (%)",
    "money.noSources": "No sources added. Click Source to add.",
    "money.noCategories": "No categories added. Click Category to add.",
    "money.annualReport": "Annual Summary",
    "money.reportDesc": "Consolidated financial view",
    "money.settingsTitle": "Financial Settings",
    "money.settingsDesc": "Manage sources and categories",
    "ecosystem.title": "Ecosystem Hub",
    "ecosystem.name": "Name",
    "ecosystem.noLinks": "No links in this category",
    "ecosystem.companies": "Companies",
    "ecosystem.links": "Links",
    "ecosystem.allCompanies": "All companies",
    "ecosystem.clearSelection": "Clear selection",
    "ecosystem.subCompanies": "sub-companies",
    "ecosystem.addSubCompany": "Add sub-company",
    "ecosystem.unlinkedSatellites": "Unlinked satellites",
    "ecosystem.noCompanies": "No companies yet",
    "settings.accounts": "Accounts",
    "settings.expenseCategories": "Expense Cat.",
    "settings.incomeCategories": "Income Cat.",
    "settings.incomeTypes": "Income Types",
    "settings.addItem": "Add",
    "settings.noItems": "No items registered",
    "settings.actions": "Actions",
    "priority.critical": "Critical",
    "priority.high": "High",
    "priority.medium": "Medium",
    "priority.low": "Low",
    "home.summary": "Here's your business ecosystem summary",
    "home.monthlyIncome": "Monthly Income",
    "home.monthlyExpenses": "Monthly Expenses",
    "home.monthlyBalance": "Monthly Balance",
    "home.ecosystemLinks": "Ecosystem Links",
    "home.companies": "Companies",
    "home.companiesRegistered": "companies registered",
    "home.documents": "Documents",
    "home.documentsSaved": "documents saved",
    "home.godModeActive": "God Mode Active",
    "home.godModeDesc": "Your second mind is ready. Control everything by voice or text.",
    "home.activate": "Activate",
    "home.aiAssistant": "AI Assistant",
    "home.tipTitle": "God Mode Tip",
    "home.tipDesc": "Try saying \"Show my financial summary\" or \"What are my most important links?\" in God Mode for quick insights.",
    "home.quickActions": "Quick Actions",
    "home.profitLoss": "Profit & Loss",
    "home.netIncome": "Net Income",
    "home.consolidatedView": "Consolidated View",
    "money.importStatement": "Import Statement",
    "money.importBankStatement": "Import Bank Statement",
    "money.selectFile": "Select File",
    "money.dropOrClick": "Drop file here or click to upload",
    "money.transactions": "transactions",
    "money.changeFile": "Change file",
    "money.defaultSource": "Default Source",
    "money.defaultCategory": "Default Category",
    "money.import": "Import",
    "money.transactionsImported": "transactions imported",
    "money.errorParseFile": "Error parsing file",
    "money.selectTransactions": "Select at least one transaction",
    "money.errorImport": "Error importing transactions",
    "common.date": "Date",
    "common.description": "Description",
    "documents.title": "Documents",
    "documents.saved": "documents saved",
    "documents.search": "Search documents...",
    "documents.category": "Category",
    "documents.all": "All",
    "documents.add": "Add",
    "documents.addDocument": "Add Document",
    "documents.upload": "Upload",
    "documents.link": "Link",
    "documents.name": "Name",
    "documents.fileUrl": "File URL",
    "documents.noDocuments": "No documents found",
    "documents.clickToAdd": "Click \"Add\" to create your first document",
    "documents.noDocCategory": "No documents",
    "documents.contracts": "Contracts",
    "documents.invoices": "Invoices",
    "documents.receipts": "Receipts",
    "documents.legal": "Legal Documents",
    "documents.financial": "Financial",
    "documents.other": "Other",
    "documents.categories": "Categorías",
    "documents.manageCategories": "Gestionar Categorías",
    "documents.newCategoryName": "Nombre de nueva categoría",
    "documents.customCategories": "Categorías Personalizadas",
    "documents.noCustomCategories": "Sin categorías personalizadas. ¡Crea una arriba!",
    "documents.defaultCategories": "Categorías Predeterminadas",
    "documents.categoryExists": "La categoría ya existe",
    "documents.categoryAdded": "¡Categoría añadida!",
    "settings.selectCompany": "Editar Empresa",
    "settings.globalSettings": "Configuración Global",
    "assistant.hello": "Hello!",
    "assistant.howCanHelp": "How can I help you today?",
    "assistant.listening": "Listening... speak naturally",
    "assistant.reviewSend": "Review and press Enter or click send",
    "assistant.typeOrMic": "Type or click the mic...",
    "assistant.speechHere": "Your speech will appear here...",
    "toast.companyUpdated": "Company updated!",
    "toast.companyCreated": "Company created!",
    "toast.errorSaving": "Error saving",
    "toast.fillRequired": "Please fill all required fields",
    "toast.linkAdded": "Link added!",
    "toast.errorAdding": "Error adding",
    "toast.linkRemoved": "Link removed!",
    "toast.errorRemoving": "Error removing",
    "toast.companyRemoved": "Company removed!",
    "common.optional": "optional",
    "company.type": "Type",
    "company.mainCompany": "Main Company",
    "company.subsidiary": "Subsidiary/Related",
    "company.parentCompany": "Parent Company",
    "company.selectParent": "Select parent company...",
    "company.name": "Company Name",
    "company.satellite": "Satellite",
    "company.about": "About",
    "company.aboutPlaceholder": "Describe your company, mission, and services...",
    "company.logoUrl": "Logo URL",
    "company.overview": "Overview",
    "company.manage": "Manage",
    "company.tips": "Tips",
    "company.employees": "Employees",
    "company.clients": "Clients",
    "company.providers": "Providers",
    "company.aboutTitle": "About Company",
    "company.noDescription": "No description added yet. Click edit to add one.",
    "company.active": "Active",
    "company.tipsTitle": "Getting Started",
    "company.tipsDesc": "Here are some tips to help you manage your company effectively.",
    "company.tipEmployees": "Add employees to track your team members, their roles, and hourly rates.",
    "company.tipClients": "Register clients to manage your customer relationships and contacts.",
    "company.tipDocuments": "Upload important documents like contracts, invoices, and receipts.",
    "company.tipFinances": "Set up income sources and expense categories to track your finances.",
    "company.quickActions": "Quick Actions",
    "company.addEmployee": "+ Employee",
    "company.addClient": "+ Client",
    "company.addDocument": "+ Document",
    "company.websiteUrl": "Website",
    "company.contactEmail": "Email",
    "company.contactPhone": "Phone",
    "company.socialLinks": "Social Links",
    "company.services": "Services",
    "company.servicesPlaceholder": "List your main services...",
    "company.coverImage": "Cover Image URL",
    "company.mission": "Mission",
    "company.missionPlaceholder": "What is your company's mission?",
    "company.portfolio": "Portfolio",
    "admin.tenants": "Admin - Tenants",
    "admin.tenantsDesc": "Manage all platform clients/tenants",
    "admin.newTenant": "New Tenant",
    "admin.searchTenants": "Search by name, slug or email...",
    "admin.totalTenants": "Total Tenants",
    "admin.active": "Active",
    "admin.inactive": "Inactive",
    "admin.tenant": "Tenant",
    "admin.domain": "Domain",
    "admin.owner": "Owner",
    "admin.status": "Status",
    "admin.share": "Share",
    "admin.actions": "Actions",
    "admin.noTenantFound": "No tenant found",
    "admin.noTenantRegistered": "No tenant registered",
    "admin.activeStatus": "Active",
    "admin.inactiveStatus": "Inactive",
    "admin.copyLink": "Copy link",
    "admin.sendWhatsApp": "Send via WhatsApp",
    "admin.sendEmail": "Send via Email",
    "admin.generatePDF": "Generate PDF",
    "admin.remixGuide": "Remix Guide",
    "admin.editTenant": "Edit Tenant",
    "admin.createTenant": "Create Tenant",
    "admin.updateInfo": "Update tenant information",
    "admin.fillData": "Fill in the data to create a new tenant",
    "admin.name": "Name",
    "admin.slug": "Slug",
    "admin.customDomain": "Custom Domain",
    "admin.ownerName": "Owner Name",
    "admin.email": "Email",
    "admin.phoneWhatsApp": "Phone (WhatsApp)",
    "admin.businessType": "Business Type",
    "admin.primaryColor": "Primary Color",
    "admin.logoUrl": "Logo URL",
    "admin.requiredFields": "Name and slug are required",
    "admin.tenantUpdated": "Tenant updated!",
    "admin.tenantCreated": "Tenant created!",
    "admin.slugExists": "Slug or domain already exists",
    "admin.errorSaving": "Error saving tenant",
    "admin.confirmDelete": "Confirm Deletion",
    "admin.deleteWarning": "Are you sure you want to delete this tenant? This action cannot be undone and all associated data will be lost.",
    "admin.tenantRemoved": "Tenant removed!",
    "admin.errorDeleting": "Error deleting tenant",
    "admin.tenantActivated": "Tenant activated",
    "admin.tenantDeactivated": "Tenant deactivated",
    "admin.errorUpdating": "Error updating tenant",
    "admin.errorLoading": "Error loading tenants",
    "admin.accessDenied": "Access denied. Only super admins can access this page.",
    "admin.linkCopied": "Link copied!",
    "admin.remixGuideTitle": "Remix Guide",
    "admin.remixGuideDesc": "Follow the steps below to create an isolated project for this client",
    "admin.clientData": "CLIENT DATA",
    "admin.stepByStep": "STEP BY STEP",
    "admin.step1Title": "Remix the Project",
    "admin.step1Desc": "Click on project name → Settings → Remix",
    "admin.step2Title": "Activate Lovable Cloud",
    "admin.step2Desc": "In the new project, activate Cloud for isolated database",
    "admin.step3Title": "Customize",
    "admin.step3Desc": "Change colors and add logo if needed",
    "admin.step4Title": "Configure Domain",
    "admin.step4Desc": "Settings → Domains → Add",
    "admin.step5Title": "Transfer to Client",
    "admin.step5Desc": "Settings → Transfer → Send to",
    "admin.copyChecklist": "Copy Checklist",
    "admin.close": "Close",
    "admin.infoCopied": "Information copied!",
    "admin.cleaning": "Cleaning",
    "admin.restaurant": "Restaurant",
    "admin.construction": "Construction",
    "admin.retail": "Retail",
    "admin.tech": "Technology",
    "admin.health": "Health",
    "admin.education": "Education",
    "admin.other": "Other",
  },
};

const AppSettingsContext = createContext<AppSettingsContextType | undefined>(undefined);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [currency, setCurrencyState] = useState(() => {
    return localStorage.getItem("app_currency") || "CAD";
  });

  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem("app_language") || "en-CA";
  });

  const setCurrency = (newCurrency: string) => {
    setCurrencyState(newCurrency);
    localStorage.setItem("app_currency", newCurrency);
    window.dispatchEvent(new Event("storage"));
  };

  const setLanguage = (newLanguage: string) => {
    setLanguageState(newLanguage);
    localStorage.setItem("app_language", newLanguage);
    document.documentElement.lang = newLanguage;
  };

  const formatCurrency = (value: number) => {
    const locales: Record<string, string> = {
      BRL: "pt-BR",
      USD: "en-US",
      EUR: "de-DE",
      GBP: "en-GB",
      CAD: "en-CA",
    };

    return new Intl.NumberFormat(locales[currency] || "en-CA", {
      style: "currency",
      currency: currency,
    }).format(value);
  };

  const t = (key: string): string => {
    const langTranslations = translations[language] || translations["en-CA"];
    return langTranslations[key] || translations["en-CA"][key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    const handleStorage = (e: StorageEvent) => {
      if (e.key === "app_currency") {
        setCurrencyState(e.newValue || "CAD");
      }
      if (e.key === "app_language") {
        setLanguageState(e.newValue || "en-CA");
      }
    };
    window.addEventListener("storage", handleStorage);
    return () => window.removeEventListener("storage", handleStorage);
  }, []);

  return (
    <AppSettingsContext.Provider
      value={{
        currency,
        setCurrency,
        language,
        setLanguage,
        formatCurrency,
        t,
      }}
    >
      {children}
    </AppSettingsContext.Provider>
  );
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (context === undefined) {
    throw new Error("useAppSettings must be used within an AppSettingsProvider");
  }
  return context;
}
